AppBundle\Entity\Currency:
    type: entity
    table: currency
    uniqueConstraints:
        UNIQ_6956883F77153098:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
        sortOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: sort_order
        icon:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdOn:
            type: datetime
            nullable: false
            column: created_on
    lifecycleCallbacks: {  }
