AppBundle\Entity\Movies:
    type: entity
    table: movies
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        year:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        rated:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        released:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        runtime:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        genre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        director:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        writer:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        actors:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        plot:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        language:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        country:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        awards:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        poster:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        metascore:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imdbrating:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imdbvotes:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imdbid:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        response:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdat:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: createdAt
        updatedat:
            type: datetime
            nullable: true
            column: updatedAt
        imdbId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: imdb_id
    lifecycleCallbacks: {  }
